= Simple Hospitality Interchange Protocol

image:https://travis-ci.org/revinate/ship-sdk.svg?branch=master["Build Status", link="https://travis-ci.org/revinate/ship-sdk"]

The Simple Hospitality Interchange Protocol, or SHIP, is a JSON-based message format, combined with a simple HTTP-based API, that aims to make it easy for hospitality-related systems and applications to exchange messages. This SDK contains the specifications for the JSON messages in both human- and machine-readable forms, plus a number of sample messages. For details on the HTTP-based API, please contact your SHIP integration partner.

== Getting the SDK

This SDK can be downloaded from the https://github.com/revinate/ship-sdk/releases[releases] page. There is one release for each version of the SHIP message specifications.

== SHIP messages

SHIP defines a small number of JSON-based messages to be used for hospitality interchange. The JSON schemata for the available message types are located in the link:schemata[] directory. The schema files located in the schemata directory can be used to validate JSON documents for conformance to SHIP. For more details about JSON schema see http://json-schema.org/.

In addition to the JSON schemata, the SHIP messages are described in more human-friendly form in the link:docs[] directory. The documentation is broken down into the following sections:

link:docs/ship-messages.adoc[SHIP messages overview]

link:docs/guest-stay.adoc[Guest-stay message]

link:docs/guest-stay-list.adoc[Guest-stay list message]

link:docs/profile.adoc[Profile message]

link:docs/simple-guest-stay.adoc[Simple guest-stay message]

link:docs/simple-guest-stay-list.adoc[Simple guest-stay list message]

link:docs/common-objects.adoc[Common objects]

link:docs/result.adoc[Result message]

link:docs/guest-stay-result.adoc[Guest-stay result message]

link:docs/guest-stay-list-result.adoc[Guest-stay list result message]

link:docs/profile-result.adoc[Profile result message]

link:docs/profile-list-result.adoc[Profile list result message]

link:docs/changelog.adoc[Revision history]

A single-page version of the documentation can also be found at https://revinate.github.io/ship-sdk/.

== Sample messages

Sample messages for each of the SHIP message types can be found in the link:samples[] directory. The sample messages therein are broken down by their message types.

== Implementations

* https://github.com/revinate/ship-java[ship-java] - Java implementation of the SHIP message types.
* https://github.com/revinate/ship-scala[ship-scala] - Scala implementation of the SHIP message types.
