= SHIP messages

SHIP defines a small number of JSON-based messages to be used for hospitality interchange. The available message types are described in the following sections.

NOTE: The *Usage* column of the object descriptions below contain one of these values: `REQUIRED`, `RECOMMENDED`,`SUGGESTED`, `OPTIONAL`, `INTERNAL`, or `DEPRECATED`. The meaning of these values are given in the following table.

.*Usage* column definitions
[cols="1,3"]
|===
|Value |Description

|`REQUIRED`
|Field must be included for the message to be considered valid

|`RECOMMENDED`
|Field should be included to enable major functionality

|`SUGGESTED`
|Field may be included to enable additional functionality

|`OPTIONAL`
|Field may be included but have minimal to no impact on functionality

|`INTERNAL`
|Field should only be included by systems that have previously agreed on its meaning

|`DEPRECATED`
|Field should not be included
|===

NOTE: The *Types* of some of the fields below are listed as `string enum`. This indicates that these fields are strings whose value can only be one of the values listed after the colon. Supplying a value not in the list will produce an invalid message.
